name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: 'jsbt v0.5.1' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/release.yml@9a270529fbbc31451aee938da7dad227ba87f828
    permissions:
      contents: read
      id-token: write
