name: Run TS tests
on:
  - push
  - pull_request
jobs:
  test-ts:
    name: 'jsbt v0.5.1' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/test.yml@9a270529fbbc31451aee938da7dad227ba87f828
